### ISSUE TITLE
Can the author provide the code for 3d svct recon?

### ISSUE THREAD

**Issue by ghost** [iwuqing/SCOPE#1]
Thanks for your impressive work. I run your code on my 2d CT dataset and it achieves the comparable performance with my re-implementation results. However, this code cannot handle the 3d SVCT reconstrcution problem, achieving inferior perfomance to our re-implementation results in the same settings. Can you provide the code for 3d svct reconsturction? Thank you so much.
ps: pyc file is very easy to decompile.

**Comment by iwuqing** [comment]
Thank you for your interest in our work. Currently, our paper only provides CT reconstruction based on 2D parallel and fan-beam projections since our baselines are based on 2D CT. I am not sure if you are referring to using this code for 3D reconstruction with parallel beam or cone beam, or performing 3D parallel beam tasks slice-by-slice using 2D CT. However, using this code directly for 3D tasks may not be feasible. Therefore, I think it is reasonable that your re-implement for 3D reconstruction can achieve better performance compared with our 2D code. Could you please provide some details about your 3D implementation?
PS: Thank you for your reminder!
